name: ci
on: [push, pull_request]

jobs:

  test:
    strategy:
      fail-fast: false
      matrix:
        go-version: [1.15.x]
        os: [macos-latest, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}
      - name: Install libappindicator
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt-get install libappindicator3-dev
      - name: Check out Git repository
        uses: actions/checkout@v3
      - name: Set up cache
        uses: actions/cache@v3
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
            ~/Library/Caches/go-build
            %LocalAppData%\go-build
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Test
        run: go test ./...

  build:
    strategy:
      fail-fast: false
      matrix:
        go-version: [1.15.x]
        os: [macos-latest, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}
      - name: Install libappindicator
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt-get install libappindicator3-dev
      - name: Check out Git repository
        uses: actions/checkout@v3
      - name: Set up cache
        uses: actions/cache@v3
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
            ~/Library/Caches/go-build
            %LocalAppData%\go-build
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Build binary
        run: go build
      - name: List artifacts
        run: ls .
      # Persist produced binaries
      # - this is not for releases, but for quick testing during the dev
      # - action artifacts can be downloaded for 90 days, then are removed by github
      - name: Attach produced packages to Github Action
        uses: actions/upload-artifact@v3
        with:
          name: go-ipfs-desktop_go-${{ matrix.go-version }}_${{ matrix.os }}
          path: go-ipfs-desktop*
          if-no-files-found: error
